<div class="advant">
	<a class="one-advant" href="/skorost-i-bezopasnost">
		<div class="sprite advant-icon speed"></div>
		<div class="one-advant-content">
			<div class="one-advant-title">
				Скорость и<br> безопасность
			</div>
			<div class="one-advant-text">
				Компания «Алло такси» гарантирует каждому клиенту безопасную, быструю и комфортную поездку,
				у нас работают только опытные водители на автомобилях, которые регулярно проходят технический
				осмотр.
			</div>
			<div class="btn yellow-btn">Подробнее</div>
		</div>
	</a>
	<a class="one-advant" href="/peregon-avto">
		<div class="sprite advant-icon transport"></div>
		<div class="one-advant-content">
			<div class="one-advant-title">
				Перегон<br> авто
			</div>
			<div class="one-advant-text">
				Перегон автомобиля или «трезвый водитель» – новая услуга в мире такси, которую
				предоставляют наши водители с многолетним опытом вождения. Мы доставим вам ваше
				авто в целости и сохранности.
			</div>
			<div class="btn yellow-btn">Подробнее</div>
		</div>
	</a>
	<a class="one-advant" href="/luchshie-tsenyi">
		<div class="sprite advant-icon price"></div>
		<div class="one-advant-content">
			<div class="one-advant-title">
				Лудшие<br> цены
			</div>
			<div class="one-advant-text">
				Тарифы в «Алло такси» оставляют приятное послевкусие от поездки. Лучшие цены и качественный
				сервис отобьет желание пользоваться другими службами такси.
			</div>
			<div class="btn yellow-btn">Подробнее</div>
		</div>
	</a>
	<a class="one-advant" href="/bonusi-i-skidki">
		<div class="sprite advant-icon bonus"></div>
		<div class="one-advant-content">
			<div class="one-advant-title">
				Скидки<br> и бонусы
			</div>
			<div class="one-advant-text">
				С заботой о постоянных клиентах, в компании «Алло такси» постоянно действует система
				скидок и различных бонусов, чтобы сделать каждую поездку еще более приятной.
			</div>
			<div class="btn yellow-btn">Подробнее</div>
		</div>
	</a>
	<a class="one-advant" href="/perevozka-gruzov">
		<div class="sprite advant-icon trucking"></div>
		<div class="one-advant-content">
			<div class="one-advant-title">
				Грузоперевозки
			</div>
			<div class="one-advant-text">
				В спектр услуг компании «Алло такси» входит перевозка грузов разных габаритов. Мы
				оперативно и бережно доставим ваш груз в любое место.
			</div>
			<div class="btn yellow-btn">Подробнее</div>
		</div>
	</a>
	<a class="one-advant" href="/beznalichnii-raschet">
		<div class="sprite advant-icon pay"></div>
		<div class="one-advant-content">
			<div class="one-advant-title">
				Безналичный<br> расчет
			</div>
			<div class="one-advant-text">
				Компания «Алло такси» идет в ногу со временем и предлагает своим клиентам безналичный
				расчет. Это отличная возможность для компаний сэкономить свои финансы.
			</div>
			<div class="btn yellow-btn">Подробнее</div>
		</div>
	</a>
</div>

<div class="shashka-container">
	<div class="shashka black"></div>
</div>