<div class="seo-text">
	<? if(isset($this->one['img']) && !empty($this->one['img'])){?>
		<img class="float-left" src="http://allotaxi.od.ua/upload/<?= $this->one['img'] ?>" alt="">
	<? } else{ ?>
		<img class="float-left" src="/usr/img/default-news.jpg" alt="">
	<? } ?>

	<?= $this->one['content'] ?>
	<div class="clear"></div>
</div>
<div class="next-prev">
	<div>
		<? if (isset($this->prev) && !empty($this->prev)){ ?>
			<a href="<?= $this->prev ?>" rel="prev">
				<div class="sprite pag-arr"></div>
				Назад
			</a>
		<? } ?>
	</div>
	<div>
		<? if (isset($this->next) && !empty($this->next)){ ?>
			<a href="<?= $this->next ?>" rel="next">
				Вперёд
				<div class="sprite pag-arr right"></div>
			</a>
		<? } ?>
	</div>
</div>