
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru-ru" lang="ru-ru" dir="ltr">
<head>
<link rel="stylesheet" type="text/css" href="/plugins/editors/jckeditor/typography/typography.php"/>
  <base href="http://allotaxi.od.ua/component/mailto/" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="алло такси Одесса,	
такси в Одессе, 	
такси Одесса,	 	
заказ такси онлаин Одесса,	
такси недорого Одесса,	
служба заказа такси Одесса,	
заказ он лаин Одесса,			
дешевое такси в Одессе,	  
экономно такси в Одессе,	
недорого такси Одесса,	
такси перевозки в Одессе,
услуги такси Одесса,		 	
заказа такси в Одессе,	 	
такси междугородние перевозки Одесса,			
такси автомобили Одесса,		
такси трансфер Одесса,			
такси проезд пассажиров Одесса,			
такси грузовые перевозки Одесса,		
заказать такси Одесса,			
перегон автомобиля Одесса,		 	
услуги драйвера Одесса,		
грузовое такси Одесса,			
такси грузовое Одесса,			
такси Одесса,		
Allo такси Одесса,			
Аllo taxi Одесса,		
Allo Одесса Одесса,			
Allo такси Одесса,  	
Allo Odessa Одесса,		 
заказать такси Одесса,			
заказ онлайн Одесса,			
онлайн taxi Одесса,			
эконом такси Одесса,			
дешевое такси  Одесса,		
работа в алло такси Одесса,	 	
дешевое такси Одесса,			
онлайн такси Одесса,			
такси хорошее Одесса,			
online такси Одесса,			
алло такси телефон Одесса," />
  <meta name="description" content="Алло Такси - Лучшее такси в Одессе. 733-5000. Круглосуточная служба такси в Одессе. Заказать такси онлайн, можно на нашем сайте. Вызов такси недорого, оперативно, качественно, надежно!" />
  <meta name="generator" content="Joomla! - Open Source Content Management" />
  <title>Алло Такси - Круглосуточная служба такси в Одессе</title>
  <link href="http://allotaxi.od.ua/component/mailto/?tmpl=component&amp;template=protostar&amp;link=09e184ec22c0cd7caa734379eca7b67efebd819c" rel="canonical" />
  <link href="/templates/protostar/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />
  <script src="/media/system/js/mootools-core.js" type="text/javascript"></script>
  <script src="/media/system/js/core.js" type="text/javascript"></script>
  <script type="text/javascript">
function keepAlive() {	var myAjax = new Request({method: "get", url: "index.php"}).send();} window.addEvent("domready", function(){ keepAlive.periodical(840000); });
  </script>

<link rel="stylesheet" href="/templates/protostar/css/template.css" type="text/css" />
<!--[if lt IE 9]>
	<script src="/media/jui/js/html5.js"></script>
<![endif]-->
</head>
<body class="contentpane modal">
	
<div id="system-message-container">
<div id="system-message">
</div>
</div>
	<script type="text/javascript">
	Joomla.submitbutton = function(pressbutton) {
		var form = document.getElementById('mailtoForm');

		// do field validation
		if (form.mailto.value == "" || form.from.value == "") {
			alert('Пожалуйста, введите корректный адрес электронной почты.');
			return false;
		}
		form.submit();
	}
</script>

<div id="mailto-window">
	<h2>
		Отправить ссылку другу.	</h2>
	<div class="mailto-close">
		<a href="javascript: void window.close()" title="Закрыть окно">
		 <span>Закрыть окно </span></a>
	</div>

	<form action="http://allotaxi.od.ua/index.php" id="mailtoForm" method="post">
		<div class="formelm">
			<label for="mailto_field">E-mail адресата</label>
			<input type="text" id="mailto_field" name="mailto" class="inputbox" size="25" value=""/>
		</div>
		<div class="formelm">
			<label for="sender_field">
			Ваше имя</label>
			<input type="text" id="sender_field" name="sender" class="inputbox" value="" size="25" />
		</div>
		<div class="formelm">
			<label for="from_field">
			Ваш E-mail</label>
			<input type="text" id="from_field" name="from" class="inputbox" value="" size="25" />
		</div>
		<div class="formelm">
			<label for="subject_field">
			Тема</label>
			<input type="text" id="subject_field" name="subject" class="inputbox" value="" size="25" />
		</div>
		<p>
			<button class="button" onclick="return Joomla.submitbutton('send');">
				Отправить			</button>
			<button class="button" onclick="window.close();return false;">
				Отмена			</button>
		</p>
		<input type="hidden" name="layout" value="default" />
		<input type="hidden" name="option" value="com_mailto" />
		<input type="hidden" name="task" value="send" />
		<input type="hidden" name="tmpl" value="component" />
		<input type="hidden" name="link" value="09e184ec22c0cd7caa734379eca7b67efebd819c" />
		<input type="hidden" name="5e1872151c446ff0d3a217b4ea3ebf51" value="1" />
	</form>
</div>

</body>
</html>
