<div class="price-list">
	<div class="price-item level1">
		<div class="price-item-title">Минимальный заказ такси в Одессе</div>
		<div class="price-item-value">32 грн</div>
	</div>
	<div class="price-item level1">
		<div class="price-item-title">Стоимость проезда по городу</div>
		<div class="price-item-value">3.80 грн/км</div>
	</div>
	<div class="price-item level1">
		<div class="price-item-title">Стоимость проезда за городом или межгород</div>
		<div class="price-item-value">6 грн/км</div>
	</div>
	<div class="price-item level1">
		<div class="price-item-title">Простой (после 10 минут)</div>
		<div class="price-item-value">1 грн/мин</div>
	</div>
	<div class="price-item level1">
		<div class="price-item-title">Почасовой заказ (заказ минимум 2 часа)</div>
		<div class="price-item-value">100 грн/час</div>
	</div>
	<div class="price-item level1">
		<div class="price-item-title">Перегон автомобиля</div>
		<div class="price-item-value">маршрут х3 грн</div>
	</div>
	<div class="price-item level1">
		<div class="price-item-title">Услуги драйвера</div>
		<div class="price-item-value">маршрут х3 грн/час</div>
	</div>
	<div class="price-item level1">
		<div class="price-item-title">Грузовое такси (заказ минимум 2 часа)</div>
		<div class="price-item-value">120 грн/час</div>
	</div>
	<div class="price-item level1">
		<div class="price-item-title">Услуги грузчиков</div>
		<div class="price-item-value">от 60 грн/час</div>
	</div>
	<div class="price-item level1">
		<div class="price-item-title">Буксировка</div>
		<div class="price-item-value">маршрут х5 грн</div>
	</div>
	<div class="price-item level1">
		<div class="price-item-title">Услуга "Трезвый водитель"</div>
		<div class="price-item-value">маршрут х3 грн</div>
	</div>
</div>